// The skills Armada delivers to every managed repository. Their files live in
// `skills/` at the root of the Armada repository and are bundled as text, so
// the single published bundle carries them. Folder hashes use the `npx skills`
// algorithm, so skills-lock.json stays readable by that tool.
import { createHash } from "node:crypto";
// Generated by bun run skills:bundle; the byte-for-byte test checks freshness.
import bundledSkills from "./skills.generated.json" with { type: "json" };

/** Where Armada's skills come from, in skills-lock.json terms. */
export const SKILLS_SOURCE = "The-Vibe-Company/armada";

export interface SkillFile {
  /** Path inside the skill folder, `/`-separated. */
  path: string;
  content: string;
}

export interface BundledSkill {
  name: string;
  delivery: "pointer" | "vendored";
  files: SkillFile[];
}

/** Every skill a repository needs to be run by Armada. A missing one is an error. */
export const BUNDLED_SKILLS: readonly BundledSkill[] = bundledSkills as BundledSkill[];

/**
 * Hash of a skill folder as `npx skills` computes it: sha256 over every file,
 * sorted by relative path, feeding the path then the content.
 */
export function skillFolderHash(files: readonly { path: string; content: string | Uint8Array }[]): string {
  const hash = createHash("sha256");
  for (const f of [...files].sort((a, b) => a.path.localeCompare(b.path))) {
    hash.update(f.path);
    hash.update(f.content);
  }
  return hash.digest("hex");
}

/** Stable discovery metadata plus instructions resolved by the installed CLI. */
export function pointerText(skill: BundledSkill, ref?: string): string {
  const main = skill.files.find((f) => f.path === "SKILL.md")?.content;
  const frontmatter = main?.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/)?.[1];
  const name = frontmatter?.match(/^name:[^\n]*/m)?.[0];
  const description = frontmatter?.match(/^description:[^\n]*(?:\n[ \t]+[^\n]*)*/m)?.[0];
  if (!name || !description) throw new Error(`skill ${skill.name} has no discovery frontmatter`);
  return `---
${name}
${description}
---

This project's Armada instructions come from the Armada CLI the brief installed. Run \`armada skill ${skill.name}\` and follow its output; for a linked file, \`armada skill ${skill.name} <file>\`. If the command is missing, install the version your brief names.

[Browse the instructions on GitHub](https://github.com/${SKILLS_SOURCE}/blob/${ref ?? "main"}/skills/${skill.name}/SKILL.md).
`;
}

/** Files kept in the project; a pointer's tag is the release recorded in its lock. */
export function deliveredSkillFiles(skill: BundledSkill, ref?: string): SkillFile[] {
  return skill.delivery === "pointer" ? [{ path: "SKILL.md", content: pointerText(skill, ref) }] : skill.files;
}
